class QWidget: ...

class QDialog(QWidget):
    class DialogCode:
        Accepted: int
        Rejected: int

    def exec(self) -> int: ...

class QLayout: ...
class QFormLayout(QLayout): ...
class QHBoxLayout(QLayout): ...
class QVBoxLayout(QLayout): ...

class QLabel(QWidget):
    def setWordWrap(self, on: bool) -> None: ...
    def setStyleSheet(self, css: str) -> None: ...

class QGroupBox(QWidget): ...

class QLineEdit(QWidget):
    class EchoMode:
        Normal: int
        NoEcho: int
        Password: int

    def setEchoMode(self, mode: int) -> None: ...
    def setPlaceholderText(self, text: str) -> None: ...
    def text(self) -> str: ...

class QTextEdit(QWidget):
    def setMaximumHeight(self, h: int) -> None: ...
    def setPlaceholderText(self, text: str) -> None: ...
    def toPlainText(self) -> str: ...
    def setPlainText(self, text: str) -> None: ...

class QComboBox(QWidget):
    def setEditable(self, on: bool) -> None: ...
    def setToolTip(self, text: str) -> None: ...
    def addItem(self, text: str) -> None: ...
    def currentText(self) -> str: ...
    def findText(self, text: str) -> int: ...
    def setCurrentIndex(self, index: int) -> None: ...

class QCheckBox(QWidget):
    def setToolTip(self, text: str) -> None: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, on: bool) -> None: ...

class QPushButton(QWidget):
    def __init__(self, text: str = ...) -> None: ...
    def setDefault(self, on: bool) -> None: ...

    class _Signal:
        def connect(self, slot: object) -> None: ...

    clicked: _Signal

class QMessageBox(QWidget):
    @staticmethod
    def warning(parent: QWidget | None, title: str, text: str) -> None: ...
