name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

env:
  PYTHON_VERSION: "3.9"

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: Set up Python
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Build .ankiaddon
        if: ${{ steps.release.outputs.release_created }}
        run: python scripts/build_ankiaddon.py

      - name: Upload asset to release
        if: ${{ steps.release.outputs.release_created }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          files: dist/*.ankiaddon
