name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.9"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Build .ankiaddon
        run: |
          python scripts/build_ankiaddon.py

      - name: Setup GitVersion
        uses: GitTools/actions/gitversion/setup@v4
        with:
          versionSpec: '6.x'

      - name: Determine version
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v4
        with:
          configFilePath: GitVersion.yml

      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          TAG=v${{ steps.gitversion.outputs.semVer }}
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists, skipping tag creation"
          else
            git tag "$TAG"
            git push origin "$TAG"
          fi

      - name: Setup GitReleaseManager
        uses: GitTools/actions/gitreleasemanager/setup@v4
        with:
          versionSpec: '0.19.x'

      - name: Generate release notes
        run: |
          echo "Release v${{ steps.gitversion.outputs.semVer }}" > release-notes.md
          echo "" >> release-notes.md
          echo "Automated release generated by CI." >> release-notes.md

      - name: Create GitHub Release
        uses: GitTools/actions/gitreleasemanager/create@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          name: v${{ steps.gitversion.outputs.semVer }}
          inputFilePath: release-notes.md
          assets: |
            dist/*.ankiaddon

